### PR TITLE
add composer support

### LINKED ISSUE #3: Composer support
@manzoorwanijk would you be open to adding support for installing this via composer? I’d be willing to submit a PR with the changes, and you would have to publish it on https://packagist.org

### PR DESCRIPTION
**Pull request by macbookandrew**
Closes #3

### CODE REVIEW

**Comment by andrewminion-luminfire** [comment]
@manzoorwanijk

**Review by manzoorwanijk — APPROVED** [review]
Thank you for the contribution and extremely sorry for missing this one.

**Comment by manzoorwanijk** [comment]
The package can be seen here

https://packagist.org/packages/manzoorwanijk/cmb2-select-plus

**Comment by macbookandrew** [comment]
Awesome; thanks! Would you mind tagging the release `1.0.0` so I can require a tagged release rather than `dev-master`?

**Comment by manzoorwanijk** [comment]
> Awesome; thanks! Would you mind tagging the release `1.0.0` so I can require a tagged release rather than `dev-master`?

Done.
https://github.com/manzoorwanijk/cmb2-select-plus/releases/tag/v1.0.0

**Pull request merged**
